version: '3.7'
services:
  public_gateways:
    build: ./gateways/public
    restart: always
    env_file:
      - .env.docker
    ports:
      - '3000:3000'
    networks:
      - default
    volumes:
      - ./gateways/public:/var/www
    command: yarn start:dev

  admin_gateways:
    build: ./gateways/admin
    restart: always
    env_file:
      - .env.docker
    ports:
      - '3001:3000'
    networks:
      - default
    volumes:
      - ./gateways/admin:/var/www
    command: yarn start:dev 

  auth_microservice:
    build: ./microservices/auth
    restart: always
    env_file:
      - .env.docker
    networks:
      - default 
    depends_on:
      - mysql_database  
    volumes:
      - ./microservices/auth:/var/www
    command: yarn start:dev

  user_microservice:
    build: ./microservices/user
    restart: always
    env_file:
      - .env.docker
    networks:
      - default 
    depends_on:
      - mysql_database  
    volumes:
      - ./microservices/user:/var/www
    command: yarn start:dev  

  mysql_database:
    image: mysql:5.6
    container_name: mysql_database
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - default  

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_management
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    restart: always
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  db_data:    
  