version: '3.7'
services:
  app:
    build: .
    restart: always
    hostname: api-gateways
    env_file:
      - .env
    ports:
      - '3000:3000'
    networks:
      - default
    volumes:
      - .:/var/www
    command: yarn start:dev

networks:
  default:
    driver: bridge
